"""Lean 4 statement and proof generator for Hidden-Law Lab worlds.

Each Hidden-Law Lab world has a finite carrier {0..n-1}, a binary operation (op
table) and a unary map (f).  All eight laws are first-order over this finite
type, so every closed proposition is decidable and can be proved (or refuted)
by ``decide``.

Usage
-----
Generate a self-contained ``.lean`` source that Lean 4 can check with no
dependencies beyond the standard library::

    from prometheus.lab.lean_layer import world_lean_source, verify_lean_source
    src = world_lean_source(HiddenLawWorld(seed=42))
    ok, err = verify_lean_source(src)          # calls lean --stdin
    assert ok, err

The generated file:
- Defines ``CarrierN`` as ``Fin n``.
- Encodes ``op`` and ``f`` as ``match`` expressions.
- For every law that **holds** in the world, emits a ``theorem`` proved by
  ``decide``.
- For every law that **does not hold**, emits a ``theorem`` of the negation,
  also proved by ``decide``.

No import is needed: ``Fin``, ``Function``, and ``decide`` are all in Lean core.
"""

from __future__ import annotations

import shutil
import subprocess
import textwrap
from pathlib import Path

from .world import HiddenLawWorld

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_LEAN_BINARY: str | None = None


def _lean_bin() -> str:
    """Return the path to the ``lean`` executable, searching PATH and ``~/.elan``."""
    global _LEAN_BINARY
    if _LEAN_BINARY is not None:
        return _LEAN_BINARY
    # Try PATH first.
    found = shutil.which("lean")
    if found:
        _LEAN_BINARY = found
        return _LEAN_BINARY
    # Fall back to elan's default toolchain location.
    elan_lean = Path.home() / ".elan" / "bin" / "lean"
    if elan_lean.exists():
        _LEAN_BINARY = str(elan_lean)
        return _LEAN_BINARY
    raise FileNotFoundError(
        "lean binary not found on PATH or in ~/.elan/bin. "
        "Install Lean 4 via elan: https://github.com/leanprover/elan"
    )


def _op_array(op: list[list[int]], n: int) -> str:
    """Render the op table as a nested Lean Array literal."""
    rows = ", ".join(
        "#[" + ", ".join(str(op[a][b]) for b in range(n)) + "]"
        for a in range(n)
    )
    return f"#[{rows}]"


def _f_array(f: list[int], n: int) -> str:
    """Render the f map as a Lean Array literal."""
    return "#[" + ", ".join(str(f[a]) for a in range(n)) + "]"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def world_lean_source(world: HiddenLawWorld) -> str:
    """Return a self-contained Lean 4 source string for *world*.

    The source contains one ``theorem`` per law (positive or negative), each
    proved by ``decide``.  It compiles with ``lean --stdin`` using only the
    core standard library.
    """
    n = len(world.symbols)
    op = world._op   # noqa: SLF001  (governor/ground-truth use only)
    f = world._f     # noqa: SLF001

    truth = world.ground_truth()

    # ------------------------------------------------------------------
    # Header
    # ------------------------------------------------------------------
    header = textwrap.dedent(f"""\
        -- Auto-generated by prometheus.lab.lean_layer
        -- World seed : {world.seed}
        -- Family     : {world.family}
        -- Map kind   : {world.map_kind}
        -- Carrier    : Fin {n}
        -- Laws       : {', '.join(f'{k}={v}' for k, v in truth.items())}

        -- No imports needed: Fin, Array, Function, and `decide` are in Lean 4 core.

        abbrev N := {n}

        private def opTable : Array (Array (Fin N)) := {_op_array(op, n)}
        def op (a b : Fin N) : Fin N := (opTable[a]!)[b]!

        private def fTable : Array (Fin N) := {_f_array(f, n)}
        def f (a : Fin N) : Fin N := fTable[a]!

    """)

    # ------------------------------------------------------------------
    # Theorems – one per law, positive or negative
    # ------------------------------------------------------------------
    theorems: list[str] = []

    # 1. commutative
    if truth["commutative"]:
        theorems.append(
            "theorem commutative : ∀ a b : Fin N, op a b = op b a := by decide"
        )
    else:
        theorems.append(
            "theorem not_commutative : ¬∀ a b : Fin N, op a b = op b a := by decide"
        )

    # 2. associative
    if truth["associative"]:
        theorems.append(
            "theorem associative : ∀ a b c : Fin N, op (op a b) c = op a (op b c) := by decide"
        )
    else:
        theorems.append(
            "theorem not_associative : ¬∀ a b c : Fin N, op (op a b) c = op a (op b c) := by decide"
        )

    # 3. has_identity
    if truth["has_identity"]:
        theorems.append(
            "theorem has_identity : ∃ e : Fin N, ∀ a : Fin N, op e a = a ∧ op a e = a := by decide"
        )
    else:
        theorems.append(
            "theorem not_has_identity : ¬∃ e : Fin N, ∀ a : Fin N, op e a = a ∧ op a e = a := by decide"
        )

    # 4. has_inverses
    if truth["has_inverses"]:
        theorems.append(
            "theorem has_inverses : "
            "(∃ e : Fin N, (∀ a : Fin N, op e a = a ∧ op a e = a) ∧ "
            "∀ a : Fin N, ∃ b : Fin N, op a b = e ∧ op b a = e) := by decide"
        )
    else:
        theorems.append(
            "theorem not_has_inverses : "
            "¬(∃ e : Fin N, (∀ a : Fin N, op e a = a ∧ op a e = a) ∧ "
            "∀ a : Fin N, ∃ b : Fin N, op a b = e ∧ op b a = e) := by decide"
        )

    # 5. idempotent
    if truth["idempotent"]:
        theorems.append(
            "theorem idempotent : ∀ a : Fin N, op a a = a := by decide"
        )
    else:
        theorems.append(
            "theorem not_idempotent : ¬∀ a : Fin N, op a a = a := by decide"
        )

    # 6. f_involution
    if truth["f_involution"]:
        theorems.append(
            "theorem f_involution : ∀ a : Fin N, f (f a) = a := by decide"
        )
    else:
        theorems.append(
            "theorem not_f_involution : ¬∀ a : Fin N, f (f a) = a := by decide"
        )

    # 7. f_homomorphism
    if truth["f_homomorphism"]:
        theorems.append(
            "theorem f_homomorphism : ∀ a b : Fin N, f (op a b) = op (f a) (f b) := by decide"
        )
    else:
        theorems.append(
            "theorem not_f_homomorphism : ¬∀ a b : Fin N, f (op a b) = op (f a) (f b) := by decide"
        )

    # 8. f_bijective
    # Function.Bijective is not decidable in Lean core; spell it out.
    if truth["f_bijective"]:
        theorems.append(
            "theorem f_injective : ∀ a b : Fin N, f a = f b → a = b := by decide\n"
            "theorem f_surjective : ∀ b : Fin N, ∃ a : Fin N, f a = b := by decide"
        )
    else:
        theorems.append(
            "theorem not_f_bijective : "
            "¬((∀ a b : Fin N, f a = f b → a = b) ∧ ∀ b : Fin N, ∃ a : Fin N, f a = b) := by decide"
        )

    return header + "\n".join(theorems) + "\n"


def verify_lean_source(source: str, timeout: int = 60) -> tuple[bool, str]:
    """Check *source* by piping it to ``lean --stdin``.

    Returns ``(True, "")`` on success or ``(False, stderr)`` on error.
    The *timeout* argument is in seconds.
    """
    lean = _lean_bin()
    try:
        result = subprocess.run(
            [lean, "--stdin"],
            input=source,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return False, f"lean --stdin timed out after {timeout}s"
    if result.returncode != 0:
        return False, result.stderr or result.stdout
    return True, ""


def verify_world(world: HiddenLawWorld, timeout: int = 60) -> tuple[bool, str]:
    """Generate and verify the Lean source for *world* in one call."""
    return verify_lean_source(world_lean_source(world), timeout=timeout)
